# Generated by Django 4.0.1 on 2023-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalcherDirect',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('activity', models.TextField(blank=True, db_column='Activity', null=True)),
                ('start', models.DateTimeField(blank=True, db_column='Start', null=True)),
                ('finish', models.DateTimeField(blank=True, db_column='Finish', null=True)),
                ('pgma', models.TextField(blank=True, db_column='PGMA', null=True)),
                ('system', models.TextField(blank=True, db_column='System', null=True)),
            ],
            options={
                'db_table': 'talcher direct',
                'managed': False,
            },
        ),
    ]
